// Generated by CoffeeScript 1.12.7
(function() {
  document.getElementById('directory-search').onkeyup = function(event) {
    if (event.keyCode === 13) {
      window.location.href = "http://localhost:8080?dir=" + document.getElementById('directory-search').value;
      return 0;
    }
  };

}).call(this);
